% This function acquires and saves a wavefrom. The waveform is saved to the
% directory defined by Resource.Parameters.saveDir with the base file name
% Resource.Parameters.saveName. An index is added which corresponds to the
% linear index into the X, Y, and Z matrices that define the 3d grid. It
% expects to find these matrices at Resource.Parameters.gridInfoFile. This
% file can be generated by the prescribe_cmp GUI.
% 
% Taylor Webb
% Fall 2019

function getWaveform(RData)
if ~exist('isSoniqConnected.m','file')
    addpath('C:\Users\Verasonics\Desktop\Taylor\Code\verasonics\Aims\lib\soniq');
    addpath('C:\Users\Verasonics\Desktop\Taylor\Code\verasonics\Aims\lib')
end

lib = 'soniq';
if ~isSoniqConnected(lib)
    openSoniq(lib);
end

Resource = evalin('base','Resource');
grid = load(Resource.Parameters.gridInfoFile);
pos = getPositionerSettings(lib);
idx = find(abs(pos.X.loc - grid.X) < 1e-6 & abs(pos.Y.loc - grid.Y) < 1e-6 & abs(pos.Z.loc - grid.Z) < 1e-6);

if Resource.Parameters.saveDir(end) ~= '\' && Resource.Parameters.saveDir(end) ~= '/'
    Resource.Parameters.saveDir(end+1) = '\';
end

getSoniqWaveform(lib,[Resource.Parameters.saveDir, Resource.Parameters.saveName, num2str(idx),'.snq']);
return