clear all; close all; clc;

%% Set up path locations
srcDirectory = setPaths();
addpath([srcDirectory,'lib\placementVerification']); % Adds library functions specific to this script

NEWINSTANCE = 0;

if NEWINSTANCE
%% Use Hardware
testArrayPlacement(...
    'C:\Users\Verasonics\Desktop\Taylor\Data\Coupling\20200320\goldStandard_skullAlone.mat',...
    'C:\Users\Verasonics\Desktop\Taylor\Data\Coupling\20200321\skullAndSponge_siliconBag.mat');
else
%% Use File
% testArrayPlacement(...
%     'C:\Users\Verasonics\Desktop\Taylor\Data\Coupling\20200320\goldStandard_skull14_zInf.mat',...
%     '',...
%     'C:\Users\Verasonics\Desktop\Taylor\Data\Coupling\20200320\skull15.mat');

testArrayPlacement(...
    'C:\Users\Verasonics\Desktop\Taylor\Data\Coupling\20200321\goldStandard_skullAlone.mat',...
    '',...
    'C:\Users\Verasonics\Desktop\Taylor\Data\Coupling\20200321\skullAndSponge_siliconBag.mat');
end