% This function acquires and saves a wavefrom. The waveform is saved to the
% directory defined by Resource.Parameters.saveDir with the base file name
% Resource.Parameters.saveName. An index is added which corresponds to the
% linear index into the X, Y, and Z matrices that define the 3d grid. It
% expects to find these matrices at Resource.Parameters.gridInfoFile. This
% file can be generated by the prescribe_cmp GUI.
% 
% Taylor Webb
% Fall 2019

function getWaveform_exVivoScan(RData)
if ~exist('isSoniqConnected.m','file')
    addpath('C:\Users\Verasonics\Desktop\Taylor\Code\verasonics\Aims\lib\soniq');
    addpath('C:\Users\Verasonics\Desktop\Taylor\Code\verasonics\Aims\lib')
end
% keyboard
lib = 'soniq';
if ~isSoniqConnected(lib)
    openSoniq(lib);
end

Resource = evalin('base','Resource');

% keyboard

if Resource.Parameters.saveDir(end) ~= '\' && Resource.Parameters.saveDir(end) ~= '/'
    Resource.Parameters.saveDir(end+1) = '\';
end
lib = 'soniq';
pos = getPositionerSettings(lib);

angles = Resource.Parameters.angles;

idx = find(abs(pos.THETA.loc - angles) < 1e-6);
fname = 'C:\Users\Verasonics\Desktop\Taylor\Code\verasonics\SingleElement\lib\OscopeParams.txt';
calllib(lib,'LoadScopeSettings',fname);
getSoniqWaveform(lib,[Resource.Parameters.saveDir, Resource.Parameters.saveName, num2str(idx),'.snq']);

disp(['HERE!, idx=', num2str(idx)])
return