% This function acquires and saves a wavefrom. The waveform is saved to the
% directory defined by Resource.Parameters.saveDir with the base file name
% Resource.Parameters.saveName. An index is added which corresponds to the
% linear index into the X, Y, and Z matrices that define the 3d grid. It
% expects to find these matrices at Resource.Parameters.gridInfoFile. This
% file can be generated by the prescribe_cmp GUI.
% 
% Taylor Webb
% Fall 2019

function saveRfDataNoScope_exVivoScan(RData)
Resource = evalin('base','Resource'); 
Trans = evalin('base','Trans'); 
Receive = evalin('base','Receive'); 

%% Determine where we are in the code - how should this be saved?
transmitIdx = Resource.Parameters.curExcitation;

% Add a slash if necessary to the end of the path
if Resource.Parameters.saveDir(end) ~= '\' && Resource.Parameters.saveDir(end) ~= '/'
    Resource.Parameters.saveDir(end+1) = '\';
end

% Figure out what angle we are currently on
lib = 'soniq';
pos = getPositionerSettings(lib);
angles = Resource.Parameters.angles;
angleIdx = find(abs(pos.THETA.loc - angles) < 1e-6);

% Create a save name based on the transmit, average, and angle number of
% the current file.
newSaveDir = [Resource.Parameters.saveDir, 'Angle', num2str(angleIdx,'%03d'), '\Transmit', num2str(transmitIdx), '\'];
if ~exist(newSaveDir, 'dir')
    mkdir(newSaveDir);
end
saveName = [newSaveDir, Resource.Parameters.saveName,'_TxData.mat'];

% Acquire the waveform
%store only the channels of interest
choi = [1 97];
RData = RData(:, choi); %help to reduce the total file size by about a factor of 4
save(saveName, 'RData','Resource','Trans','Receive');

disp(['  Transmit ', num2str(transmitIdx), ' is complete.']);